/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Greet: typeof import('./src/components/Greet.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Index: typeof import('./src/components/Index.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu.vue')['default']
    Music: typeof import('./src/components/Music.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongList: typeof import('./src/components/SongList.vue')['default']
    Translate: typeof import('./src/components/Translate.vue')['default']
  }
}
